<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search mantenimientos
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["mantenimientos/new", "Create mantenimientos"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "mantenimientos/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdmantenimiento" class="col-sm-2 control-label">IdMantenimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idMantenimiento", "type" => "number", "class" => "form-control", "id" => "fieldIdmantenimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombremantenimiento" class="col-sm-2 control-label">NombreMantenimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreMantenimiento", "size" => 30, "class" => "form-control", "id" => "fieldNombremantenimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechainicio" class="col-sm-2 control-label">FechaInicio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaInicio", "type" => "date", "class" => "form-control", "id" => "fieldFechainicio"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechafin" class="col-sm-2 control-label">FechaFin</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaFin", "type" => "date", "class" => "form-control", "id" => "fieldFechafin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCostomantenimiento" class="col-sm-2 control-label">CostoMantenimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["costoMantenimiento", "size" => 30, "class" => "form-control", "id" => "fieldCostomantenimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVotomantenimiento" class="col-sm-2 control-label">VotoMantenimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["votoMantenimiento", "type" => "number", "class" => "form-control", "id" => "fieldVotomantenimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIddepartamento" class="col-sm-2 control-label">IdDepartamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idDepartamento", "type" => "number", "class" => "form-control", "id" => "fieldIddepartamento"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
