<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["login/index", "Menú Principal"]); ?></li>
            <li class="previous"><?php echo $this->tag->linkTo(["mantenimientos", "Regresar"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Crear mantenimientos
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "mantenimientos/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
			"enctype" => "multipart/form-data"
        ]
    );
?>


<div class="form-group">
    <label for="fieldNombremantenimiento" class="col-sm-2 control-label">Nombre del Mantenimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreMantenimiento", "size" => 30, "class" => "form-control", "id" => "fieldNombremantenimiento"]) ?>
    </div>
</div>



<div class="form-group">
    <label for="fieldFechainicio" class="col-sm-2 control-label">Fecha de Inicio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaInicio", "type" => "date","placeholder"=>"YYYY-MM-DD" ,"class" => "form-control", "id" => "fieldFechainicio"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechafin" class="col-sm-2 control-label">Fecha Fin</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaFin", "type" => "date","placeholder"=>"YYYY-MM-DD", "class" => "form-control", "id" => "fieldFechafin"]) ?>
   </div>
</div>


<div class="form-group">
    <label for="fieldCostomantenimiento" class="col-sm-2 control-label">Costo de Mantenimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["costoMantenimiento", "size" => 30, "class" => "form-control", "id" => "fieldCostomantenimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldVotomantenimiento" class="col-sm-2 control-label">Voto Mantenimiento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->hiddenField(["value"=>0,"votoMantenimiento", "type" => "number", "class" => "form-control", "id" => "fieldVotomantenimiento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImageFile" class="col-sm-2 control-label">Upload Image</label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(["imageFile", "size" => 30, "class" => "form-control", "id" => "fieldImageFile"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIddepartamento" class="col-sm-2 control-label">Numero Departamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idDepartamento", "type" => "number", "class" => "form-control", "id" => "fieldIddepartamento"]) ?>
    </div>
</div>




<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
