<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Buscar Pagos
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["pagos/new", "Crear Pago"]) ?>
        <li class="previous"><?php echo $this->tag->linkTo(["login/index", "Menú Principal"]); ?></li>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "pagos/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdpago" class="col-sm-2 control-label">Identificador Pago</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idPago", "type" => "number", "class" => "form-control", "id" => "fieldIdpago"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPagoalicuta" class="col-sm-2 control-label">Pago Alicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["pagoAlicuta", "size" => 30, "class" => "form-control", "id" => "fieldPagoalicuta"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechaalicuota" class="col-sm-2 control-label">Fecha de Alicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaAlicuota", "type" => "date", "class" => "form-control", "id" => "fieldFechaalicuota"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPenalidadalicuota" class="col-sm-2 control-label">Penalidad de Alicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["penalidadAlicuota", "size" => 30, "class" => "form-control", "id" => "fieldPenalidadalicuota"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTotalalicuota" class="col-sm-2 control-label">Total Alicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["totalAlicuota", "size" => 30, "class" => "form-control", "id" => "fieldTotalalicuota"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIddepartamento" class="col-sm-2 control-label">Numero Departamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idDepartamento", "type" => "number", "class" => "form-control", "id" => "fieldIddepartamento"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
