<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["pagos", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create pagos
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "pagos/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPagoalicuta" class="col-sm-2 control-label">PagoAlicuta</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["pagoAlicuta", "size" => 30, "class" => "form-control", "id" => "fieldPagoalicuta"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechaalicuota" class="col-sm-2 control-label">FechaAlicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaAlicuota", "type" => "date", "class" => "form-control", "id" => "fieldFechaalicuota"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPenalidadalicuota" class="col-sm-2 control-label">PenalidadAlicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["penalidadAlicuota", "size" => 30, "class" => "form-control", "id" => "fieldPenalidadalicuota"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTotalalicuota" class="col-sm-2 control-label">TotalAlicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["totalAlicuota", "size" => 30, "class" => "form-control", "id" => "fieldTotalalicuota"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIddepartamento" class="col-sm-2 control-label">IdDepartamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idDepartamento", "type" => "number", "class" => "form-control", "id" => "fieldIddepartamento"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
