<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["pagos", "Regresar"]) ?></li>
            <li class="previous"><?php echo $this->tag->linkTo(["login/index", "Menú Principal"]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Crear Pago
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "pagos/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPagoalicuta" class="col-sm-2 control-label">Valor Alicuta</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["pagoAlicuta", "size" => 30, "class" => "form-control", "id" => "fieldPagoalicuta"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechaalicuota" class="col-sm-2 control-label">Fecha de Pago Alicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaAlicuota","placeholder"=>"YYYY-MM-DD", "type" => "date", "class" => "form-control", "id" => "fieldFechaalicuota"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPenalidadalicuota" class="col-sm-2 control-label">Penalidad Alicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["value"=>"0.05","penalidadAlicuota", "size" => 30, "class" => "form-control", "id" => "fieldPenalidadalicuota"]) ?>
    </div> 
</div>

<div class="form-group">
    <label for="fieldTotalalicuota" class="col-sm-2 control-label">Total Alicuota</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["value"=>"0","totalAlicuota", "size" => 30, "class" => "form-control", "id" => "fieldTotalalicuota"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIddepartamento" class="col-sm-2 control-label">Numero Departamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idDepartamento", "type" => "number", "class" => "form-control", "id" => "fieldIddepartamento"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
