<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
			<li class="previous"><?php echo $this->tag->linkTo(["login/index", "Menú Principal"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["departamentos/new", "Crear Departamento "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Lista Departamentos</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Identificador Departamento</th>
            <th>Numero Departamento</th>
            <th>Numero Telefono</th>
            <th>Usuario</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $departamento): ?>
            <tr>
                <td><?php echo $departamento->getIddepartamento() ?></td>
            <td><?php echo $departamento->getNumerodepartamento() ?></td>
            <td><?php echo $departamento->getNumerotelefono() ?></td>
            <td><?php echo $departamento->getIdUsuario()?></td>
                <td><?php echo $this->tag->linkTo(["departamentos/edit/" . $departamento->getIddepartamento(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["departamentos/delete/" . $departamento->getIddepartamento(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
		
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("departamentos/search", "Primera") ?></li>
                <li><?php echo $this->tag->linkTo("departamentos/search?page=" . $page->before, "Anterior") ?></li>
                <li><?php echo $this->tag->linkTo("departamentos/search?page=" . $page->next, "Siguiente") ?></li>
                <li><?php echo $this->tag->linkTo("departamentos/search?page=" . $page->last, "Ultima") ?></li>
            </ul>
        </nav>
    </div>
</div>
