<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search eventos
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["eventos/new", "Create eventos"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "eventos/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdevento" class="col-sm-2 control-label">IdEvento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idEvento", "type" => "number", "class" => "form-control", "id" => "fieldIdevento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombreevento" class="col-sm-2 control-label">NombreEvento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreEvento", "size" => 30, "class" => "form-control", "id" => "fieldNombreevento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHorainicio" class="col-sm-2 control-label">HoraInicio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["horaInicio", "size" => 30, "class" => "form-control", "id" => "fieldHorainicio"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHorafin" class="col-sm-2 control-label">HoraFin</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["horaFin", "size" => 30, "class" => "form-control", "id" => "fieldHorafin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechaevento" class="col-sm-2 control-label">FechaEvento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaEvento", "type" => "date", "class" => "form-control", "id" => "fieldFechaevento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIddepartamento" class="col-sm-2 control-label">IdDepartamento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["idDepartamento", "type" => "number", "class" => "form-control", "id" => "fieldIddepartamento"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
