<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["login/index", "Menú Principal"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["eventos/new", "Crear Evento "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Listado Eventos</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Evento</th>
            <th>Nombre de Evento</th>
            <th>HoraInicio</th>
            <th>HoraFin</th>
            <th>Fecha Evento</th>
            <th>Numero Departamento</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $evento): ?>
            <tr>
                <td><?php echo $evento->getIdevento() ?></td>
            <td><?php echo $evento->getNombreevento() ?></td>
            <td><?php echo $evento->getHorainicio() ?></td>
            <td><?php echo $evento->getHorafin() ?></td>
            <td><?php echo $evento->getFechaevento() ?></td>
            <td><?php echo $evento->getIddepartamento() ?></td>

                <td><?php echo $this->tag->linkTo(["eventos/edit/" . $evento->getIdevento(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["eventos/delete/" . $evento->getIdevento(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("departamentos/search", "Primera") ?></li>
                <li><?php echo $this->tag->linkTo("departamentos/search?page=" . $page->before, "Anterior") ?></li>
                <li><?php echo $this->tag->linkTo("departamentos/search?page=" . $page->next, "Siguiente") ?></li>
                <li><?php echo $this->tag->linkTo("departamentos/search?page=" . $page->last, "Ultima") ?></li>
            </ul>
        </nav>
    </div>
</div>
