<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Menú Principal
    </h1>
</div>
<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["departamentos/search", "Departamento"]); ?></li>
			<li class="previous"><?php echo $this->tag->linkTo(["mantenimientos/search", "Mantenimiento"]); ?></li>
			<li class="previous"><?php echo $this->tag->linkTo(["pagos/search", "Pagos"]); ?></li>
			<li class="previous"><?php echo $this->tag->linkTo(["eventos/search", "Eventos"]); ?></li>
			<li class="Exit"><?php echo $this->tag->linkTo(["login/logout", "Salir Sesión"]); ?></li>
           
        </ul>
    </nav>
</div>
<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "login/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Nombre de Usuario</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Buscar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
