<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["login/index", "Menú Principal"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["login/new", "Crear Nuevo Usuario"]); ?></li>
			
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Usuarios Registrados</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Identificador</th>
            <th>Username</th>
            <th>Contraseña</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
            <th>Rol</th>
            <th>Validationkey</th>
            <th>Status</th>
            <th>Fecha Creación</th>
            <th>Fecha Actualización</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $login): ?>
            <tr>
                <td><?php echo $login->getId() ?></td>
            <td><?php echo $login->getUsername() ?></td>
            <td><?php echo $login->getPassword() ?></td>
            <td><?php echo $login->getFirstname() ?></td>
            <td><?php echo $login->getSurname() ?></td>
            <td><?php echo $login->getEmailaddress() ?></td>
            <td><?php echo $login->getRole() ?></td>
            <td><?php echo $login->getValidationkey() ?></td>
            <td><?php echo $login->getStatus() ?></td>
            <td><?php echo $login->getCreatedat() ?></td>
            <td><?php echo $login->getUpdatedat() ?></td>

                <td><?php echo $this->tag->linkTo(["login/edit/" . $login->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["login/delete/" . $login->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("login/search", "Primera") ?></li>
                <li><?php echo $this->tag->linkTo("login/search?page=" . $page->before, "Anterior") ?></li>
                <li><?php echo $this->tag->linkTo("login/search?page=" . $page->next, "Siguiente") ?></li>
                <li><?php echo $this->tag->linkTo("login/search?page=" . $page->last, "Ultima") ?></li>
            </ul>
        </nav>
    </div>
</div>
